### ISSUE TITLE
Additional - On Page Load

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/find_your_drink#12]
(On first page load, or if storage setting does not exist)

When user loads page, they are asked whether they are 19 or over

- [x] If no, user setting would be stored to only display non-alcoholic drinks

- [x] If yes, the user setting would be stored to display all available drinks

**Comment by PrimalOrB** [comment]
## Description
Interact with storage from #13 


If storage item not found, create empty {} object with presumed default values

**Comment by MarilynPapadopoulos** [comment]
Is this going to be a modal?
