### ISSUE TITLE
MVP - Cocktails API

### ISSUE THREAD

**Issue by PrimalOrB** [PrimalOrB/find_your_drink#2]
For our MVP, we want to be able to:
- [x] Retrieve a random cocktail
- [x] Retrieve the photo of the cocktail
- [x] Retrieve the ingredients / recipe for the cocktail
- [x] Retrieve the ingredient images for the recipe

This work can happen before HTML hooks are known for display

**Comment by PrimalOrB** [comment]
Related acceptance criteria as per Project overview

- [ ] Use at least two server-side APIs.

**Comment by PrimalOrB** [comment]
https://www.thecocktaildb.com/api.php

## Description
 we can use the test API key '1' for educational purposes 
* can search by: | 
  *  cocktail name
  *  cocktail first letter
   *  ingredient name (this is where we could maybe pick some themed ingredients for the monthly themes, like color)
  *  lookup cocktail details by id
  *  lookup ingredients by id
  *  look up random cocktail (probably where we start)
  *  search by ingredient
  *  filter by alcoholic / non alcoholic
   *  search by category
   *  filter by glass
   *  images / thumbnails

## Random Cocktail Example:
https://www.thecocktaildb.com/api/json/v1/1/random.php
( store drink ID for looking up recipe, ingredients, images, etc)

**Comment by MarilynPapadopoulos** [comment]
I suggest we use the "search by ingredient".  Add a field in the form that allows the user to choose a base alcohol for the cocktail.  Then choose a random cocktail associated with that base alcohol.  This is also accompanied by an image
https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=Gin

**Comment by PrimalOrB** [comment]
In my mind for the MVP version, simply displaying a random cocktail would be sufficient, rather than worrying about the query parameters. That really is the core functionality if considering a story like

```
WHEN the page loads
THEN I am presented with a drink
```

Certainly in the Additional feature sets, adding more power to the search would be the plan.

Thoughts?   I agree - Marilyn
